# Importing Dependancies

In [1]:
%matplotlib notebook 
%matplotlib inline

import os
import csv
import random
import string
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import requests
import zipfile
from scipy.stats import linregress
import glob

# Reading Files & Creating DataFrames

In [2]:
#Air Quality Index DataFrame
aqi_df = pd.read_csv("../Output/aqi_compiled.csv")

# Analysis & Workings

In [3]:
aqi_df

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days SO2,Days PM2.5,Days PM10
0,Alabama,Autauga,1980,179,122,35,18,4,0,0,177,108,40,0,0,122,57,0,0
1,Alabama,Colbert,1980,274,127,45,63,39,0,0,200,165,56,0,0,0,274,0,0
2,Alabama,Jackson,1980,366,85,110,92,79,0,0,200,200,94,0,0,0,366,0,0
3,Alabama,Jefferson,1980,343,171,109,37,19,7,0,221,140,51,207,0,136,0,0,0
4,Alabama,Lauderdale,1980,274,120,58,77,19,0,0,200,139,56,0,0,0,274,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38474,Wyoming,Sublette,2019,210,127,72,8,3,0,0,200,84,49,0,0,208,0,2,0
38475,Wyoming,Sweetwater,2019,273,210,60,3,0,0,0,133,61,43,0,3,165,0,3,102
38476,Wyoming,Teton,2019,244,209,35,0,0,0,0,87,54,44,1,0,240,0,3,0
38477,Wyoming,Uinta,2019,181,146,34,1,0,0,0,101,58,44,0,0,178,0,0,3
38478,Wyoming,Weston,2019,181,161,20,0,0,0,0,71,51,42,0,0,179,2,0,0

In [4]:
NY_df = aqi_df.loc[aqi_df["State"] == "New York"]

In [5]:
NY_df

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days SO2,Days PM2.5,Days PM10
349,New York,Albany,1980,175,47,74,51,3,0,0,178,114,75,0,0,0,175,0,0
350,New York,Bronx,1980,350,176,122,52,0,0,0,137,106,50,5,36,0,309,0,0
351,New York,Broome,1980,365,218,118,22,7,0,0,177,93,44,10,0,147,208,0,0
352,New York,Chautauqua,1980,338,130,101,79,28,0,0,200,144,66,0,0,0,338,0,0
353,New York,Chemung,1980,359,291,53,13,2,0,0,187,71,36,10,0,226,123,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38044,New York,Steuben,2019,274,263,11,0,0,0,0,62,47,37,2,0,232,0,40,0
38045,New York,Suffolk,2019,273,215,49,9,0,0,0,150,71,43,0,0,245,0,28,0
38046,New York,Tompkins,2019,242,236,6,0,0,0,0,61,45,37,0,0,206,36,0,0
38047,New York,Wayne,2019,208,193,15,0,0,0,0,90,49,39,0,0,208,0,0,0
38048,New York,Westchester,2019,273,240,32,1,0,0,0,105,58,38,0,0,241,0,32,0

In [6]:
NY_2018_df = NY_df.loc[NY_df["Year"] == 2018]

In [7]:
NY_2018_df

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days SO2,Days PM2.5,Days PM10
36990,New York,Albany,2018,365,292,71,2,0,0,0,112,59,38,0,0,216,0,149,0
36991,New York,Bronx,2018,365,286,70,9,0,0,0,150,64,39,0,80,169,0,116,0
36992,New York,Chautauqua,2018,362,311,47,4,0,0,0,126,58,36,0,0,336,4,22,0
36993,New York,Dutchess,2018,364,342,20,1,1,0,0,156,46,31,0,0,348,16,0,0
36994,New York,Erie,2018,365,276,87,2,0,0,0,112,65,40,0,17,204,0,144,0
36995,New York,Essex,2018,365,319,44,2,0,0,0,108,54,41,0,0,363,0,2,0
36996,New York,Franklin,2018,341,341,0,0,0,0,0,24,0,0,0,0,0,341,0,0
36997,New York,Hamilton,2018,357,346,11,0,0,0,0,97,45,33,0,0,352,5,0,0
36998,New York,Herkimer,2018,248,236,12,0,0,0,0,93,48,36,0,0,245,3,0,0
36999,New York,Jefferson,2018,329,307,20,2,0,0,0,105,47,33,0,0,329,0,0,0
37000,New York,Kings,2018,365,330,35,0,0,0,0,80,49,25,0,0,0,0,365,0
37001,New York,Monroe,2018,365,301,60,4,0,0,0,108,58,36,0,6,205,0,154,0
37002,New York,Nassau,2018,365,340,25,0,0,0,0,92,45,21,0,0,0,7,358,0
37003,New York,New York,2018,365,255,99,10,1,0,0,151,66,41,0,0,142,0,223,0
37004,New York,Niagara,2018,320,294,25,1,0,0,0,101,50,34,0,0,320,0,0,0
37005,New York,Oneida,2018,364,347,17,0,0,0,0,70,43,18,0,0,0,0,364,0
37006,New York,Onondaga,2018,365,319,44,2,0,0,0,115,57,35,0,0,310,1,54,0
37007,New York,Orange,2018,365,323,41,1,0,0,0,147,53,35,0,0,261,0,104,0
37008,New York,Oswego,2018,350,324,25,1,0,0,0,112,47,32,0,0,350,0,0,0
37009,New York,Putnam,2018,352,332,18,1,1,0,0,151,45,31,0,0,337,15,0,0
37010,New York,Queens,2018,365,288,69,8,0,0,0,140,60,39,0,66,170,0,129,0
37011,New York,Richmond,2018,363,286,71,6,0,0,0,136,61,37,0,0,132,0,231,0
37012,New York,Rockland,2018,365,320,39,5,0,1,0,210,54,35,0,0,302,0,63,0
37013,New York,Saratoga,2018,361,341,19,1,0,0,0,119,45,31,0,0,361,0,0,0
37014,New York,Seneca,2018,364,364,0,0,0,0,0,17,0,0,0,0,0,364,0,0
37015,New York,St. Lawrence,2018,359,282,66,11,0,0,0,110,81,14,0,0,0,359,0,0
37016,New York,Steuben,2018,361,326,35,0,0,0,0,87,50,32,1,0,295,0,65,0
37017,New York,Suffolk,2018,365,300,54,10,1,0,0,172,61,39,0,0,287,0,78,0
37018,New York,Tompkins,2018,364,330,32,2,0,0,0,101,49,33,0,0,353,11,0,0
37019,New York,Wayne,2018,239,210,25,4,0,0,0,115,58,38,0,0,239,0,0,0
37020,New York,Westchester,2018,365,316,37,11,1,0,0,169,58,34,0,0,289,0,76,0

In [8]:
NewYork_df = NY_2018_df.drop(['Days CO', 'Days NO2', 'Days Ozone', 'Days SO2', 'Days PM2.5', 'Days PM10'], axis=1)

In [9]:
NewYork_df["Bad Days"] = NewYork_df["Unhealthy for Sensitive Groups Days"] + NewYork_df["Unhealthy Days"] + NewYork_df["Very Unhealthy Days"] + NewYork_df["Hazardous Days"]

In [10]:
NewYork_df["Max_AQI"] = NewYork_df["Max AQI"]

In [11]:
NewYork_df["90th_Percentile_AQI"] = NewYork_df["90th Percentile AQI"]

In [12]:
NewYork_df["Median_AQI"] = NewYork_df["Median AQI"]

In [13]:
NewYork_df

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Bad Days,Max_AQI,90th_Percentile_AQI,Median_AQI
36990,New York,Albany,2018,365,292,71,2,0,0,0,112,59,38,2,112,59,38
36991,New York,Bronx,2018,365,286,70,9,0,0,0,150,64,39,9,150,64,39
36992,New York,Chautauqua,2018,362,311,47,4,0,0,0,126,58,36,4,126,58,36
36993,New York,Dutchess,2018,364,342,20,1,1,0,0,156,46,31,2,156,46,31
36994,New York,Erie,2018,365,276,87,2,0,0,0,112,65,40,2,112,65,40
36995,New York,Essex,2018,365,319,44,2,0,0,0,108,54,41,2,108,54,41
36996,New York,Franklin,2018,341,341,0,0,0,0,0,24,0,0,0,24,0,0
36997,New York,Hamilton,2018,357,346,11,0,0,0,0,97,45,33,0,97,45,33
36998,New York,Herkimer,2018,248,236,12,0,0,0,0,93,48,36,0,93,48,36
36999,New York,Jefferson,2018,329,307,20,2,0,0,0,105,47,33,2,105,47,33
37000,New York,Kings,2018,365,330,35,0,0,0,0,80,49,25,0,80,49,25
37001,New York,Monroe,2018,365,301,60,4,0,0,0,108,58,36,4,108,58,36
37002,New York,Nassau,2018,365,340,25,0,0,0,0,92,45,21,0,92,45,21
37003,New York,New York,2018,365,255,99,10,1,0,0,151,66,41,11,151,66,41
37004,New York,Niagara,2018,320,294,25,1,0,0,0,101,50,34,1,101,50,34
37005,New York,Oneida,2018,364,347,17,0,0,0,0,70,43,18,0,70,43,18
37006,New York,Onondaga,2018,365,319,44,2,0,0,0,115,57,35,2,115,57,35
37007,New York,Orange,2018,365,323,41,1,0,0,0,147,53,35,1,147,53,35
37008,New York,Oswego,2018,350,324,25,1,0,0,0,112,47,32,1,112,47,32
37009,New York,Putnam,2018,352,332,18,1,1,0,0,151,45,31,2,151,45,31
37010,New York,Queens,2018,365,288,69,8,0,0,0,140,60,39,8,140,60,39
37011,New York,Richmond,2018,363,286,71,6,0,0,0,136,61,37,6,136,61,37
37012,New York,Rockland,2018,365,320,39,5,0,1,0,210,54,35,6,210,54,35
37013,New York,Saratoga,2018,361,341,19,1,0,0,0,119,45,31,1,119,45,31
37014,New York,Seneca,2018,364,364,0,0,0,0,0,17,0,0,0,17,0,0
37015,New York,St. Lawrence,2018,359,282,66,11,0,0,0,110,81,14,11,110,81,14
37016,New York,Steuben,2018,361,326,35,0,0,0,0,87,50,32,0,87,50,32
37017,New York,Suffolk,2018,365,300,54,10,1,0,0,172,61,39,11,172,61,39
37018,New York,Tompkins,2018,364,330,32,2,0,0,0,101,49,33,2,101,49,33
37019,New York,Wayne,2018,239,210,25,4,0,0,0,115,58,38,4,115,58,38
37020,New York,Westchester,2018,365,316,37,11,1,0,0,169,58,34,12,169,58,34

In [14]:
NewYork_2018_df = NewYork_df.drop(['Unhealthy for Sensitive Groups Days', 'Unhealthy Days', 'Very Unhealthy Days', 'Hazardous Days', 'Max AQI', '90th Percentile AQI', 'Median AQI'], axis=1)

In [15]:
NewYork_2018_df["% Good Days"]=NewYork_2018_df["Good Days"]/NewYork_2018_df["Days with AQI"]*100

In [16]:
NewYork_2018_df["% Moderate Days"]=NewYork_2018_df["Moderate Days"]/NewYork_2018_df["Days with AQI"]*100

In [17]:
NewYork_2018_df["% Bad Days"]=NewYork_2018_df["Bad Days"]/NewYork_2018_df["Days with AQI"]*100

In [18]:
NewYork_2018_df

,State,County,Year,Days with AQI,Good Days,Moderate Days,Bad Days,Max_AQI,90th_Percentile_AQI,Median_AQI,% Good Days,% Moderate Days,% Bad Days
36990,New York,Albany,2018,365,292,71,2,112,59,38,80.000000,19.452055,0.547945
36991,New York,Bronx,2018,365,286,70,9,150,64,39,78.356164,19.178082,2.465753
36992,New York,Chautauqua,2018,362,311,47,4,126,58,36,85.911602,12.983425,1.104972
36993,New York,Dutchess,2018,364,342,20,2,156,46,31,93.956044,5.494505,0.549451
36994,New York,Erie,2018,365,276,87,2,112,65,40,75.616438,23.835616,0.547945
36995,New York,Essex,2018,365,319,44,2,108,54,41,87.397260,12.054795,0.547945
36996,New York,Franklin,2018,341,341,0,0,24,0,0,100.000000,0.000000,0.000000
36997,New York,Hamilton,2018,357,346,11,0,97,45,33,96.918768,3.081232,0.000000
36998,New York,Herkimer,2018,248,236,12,0,93,48,36,95.161290,4.838710,0.000000
36999,New York,Jefferson,2018,329,307,20,2,105,47,33,93.313070,6.079027,0.607903
37000,New York,Kings,2018,365,330,35,0,80,49,25,90.410959,9.589041,0.000000
37001,New York,Monroe,2018,365,301,60,4,108,58,36,82.465753,16.438356,1.095890
37002,New York,Nassau,2018,365,340,25,0,92,45,21,93.150685,6.849315,0.000000
37003,New York,New York,2018,365,255,99,11,151,66,41,69.863014,27.123288,3.013699
37004,New York,Niagara,2018,320,294,25,1,101,50,34,91.875000,7.812500,0.312500
37005,New York,Oneida,2018,364,347,17,0,70,43,18,95.329670,4.670330,0.000000
37006,New York,Onondaga,2018,365,319,44,2,115,57,35,87.397260,12.054795,0.547945
37007,New York,Orange,2018,365,323,41,1,147,53,35,88.493151,11.232877,0.273973
37008,New York,Oswego,2018,350,324,25,1,112,47,32,92.571429,7.142857,0.285714
37009,New York,Putnam,2018,352,332,18,2,151,45,31,94.318182,5.113636,0.568182
37010,New York,Queens,2018,365,288,69,8,140,60,39,78.904110,18.904110,2.191781
37011,New York,Richmond,2018,363,286,71,6,136,61,37,78.787879,19.559229,1.652893
37012,New York,Rockland,2018,365,320,39,6,210,54,35,87.671233,10.684932,1.643836
37013,New York,Saratoga,2018,361,341,19,1,119,45,31,94.459834,5.263158,0.277008
37014,New York,Seneca,2018,364,364,0,0,17,0,0,100.000000,0.000000,0.000000
37015,New York,St. Lawrence,2018,359,282,66,11,110,81,14,78.551532,18.384401,3.064067
37016,New York,Steuben,2018,361,326,35,0,87,50,32,90.304709,9.695291,0.000000
37017,New York,Suffolk,2018,365,300,54,11,172,61,39,82.191781,14.794521,3.013699
37018,New York,Tompkins,2018,364,330,32,2,101,49,33,90.659341,8.791209,0.549451
37019,New York,Wayne,2018,239,210,25,4,115,58,38,87.866109,10.460251,1.673640
37020,New York,Westchester,2018,365,316,37,12,169,58,34,86.575342,10.136986,3.287671

In [19]:
NJ_df = aqi_df.loc[aqi_df["State"] == "New Jersey"]

In [20]:
NJ_2018_df = NJ_df.loc[NJ_df["Year"] == 2018]

In [21]:
NewJersey_df = NJ_2018_df.drop(['Days CO', 'Days NO2', 'Days Ozone', 'Days SO2', 'Days PM2.5', 'Days PM10'], axis=1)

In [22]:
NewJersey_df["Bad Days"] = NewJersey_df["Unhealthy for Sensitive Groups Days"] + NewJersey_df["Unhealthy Days"] + NewJersey_df["Very Unhealthy Days"] + NewJersey_df["Hazardous Days"]

In [23]:
NewJersey_df["Max_AQI"] = NewJersey_df["Max AQI"]

In [24]:
NewJersey_df["90th_Percentile_AQI"] = NewJersey_df["90th Percentile AQI"]

In [25]:
NewJersey_df["Median_AQI"] = NewJersey_df["Median AQI"]

In [26]:
NewJersey_2018_df = NewJersey_df.drop(['Unhealthy for Sensitive Groups Days', 'Unhealthy Days', 'Very Unhealthy Days', 'Hazardous Days', 'Max AQI', '90th Percentile AQI', 'Median AQI'], axis=1)

In [27]:
NewJersey_2018_df["% Good Days"]=NewJersey_2018_df["Good Days"]/NewJersey_2018_df["Days with AQI"]*100

In [28]:
NewJersey_2018_df["% Moderate Days"]=NewJersey_2018_df["Moderate Days"]/NewJersey_2018_df["Days with AQI"]*100

In [29]:
NewJersey_2018_df["% Bad Days"]=NewJersey_2018_df["Bad Days"]/NewJersey_2018_df["Days with AQI"]*100

In [30]:
NewJersey_2018_df

,State,County,Year,Days with AQI,Good Days,Moderate Days,Bad Days,Max_AQI,90th_Percentile_AQI,Median_AQI,% Good Days,% Moderate Days,% Bad Days
36958,New Jersey,Atlantic,2018,365,327,37,1,112,51,37,89.589041,10.136986,0.273973
36959,New Jersey,Bergen,2018,365,214,137,14,164,76,45,58.630137,37.534247,3.835616
36960,New Jersey,Camden,2018,365,237,123,5,140,68,44,64.931507,33.698630,1.369863
36961,New Jersey,Cumberland,2018,365,305,60,0,93,56,38,83.561644,16.438356,0.000000
36962,New Jersey,Essex,2018,364,277,83,4,177,64,38,76.098901,22.802198,1.098901
36963,New Jersey,Gloucester,2018,276,223,46,7,147,67,39,80.797101,16.666667,2.536232
36964,New Jersey,Hudson,2018,365,255,101,9,174,67,42,69.863014,27.671233,2.465753
36965,New Jersey,Hunterdon,2018,352,273,74,5,179,63,38,77.556818,21.022727,1.420455
36966,New Jersey,Mercer,2018,365,283,75,7,187,64,40,77.534247,20.547945,1.917808
36967,New Jersey,Middlesex,2018,365,282,77,6,133,64,38,77.260274,21.095890,1.643836
36968,New Jersey,Monmouth,2018,245,220,25,0,100,51,33,89.795918,10.204082,0.000000
36969,New Jersey,Morris,2018,365,323,37,5,136,54,34,88.493151,10.136986,1.369863
36970,New Jersey,Ocean,2018,349,296,45,8,143,61,35,84.813754,12.893983,2.292264
36971,New Jersey,Passaic,2018,277,233,41,3,150,61,37,84.115523,14.801444,1.083032
36972,New Jersey,Union,2018,365,254,111,0,95,60,42,69.589041,30.410959,0.000000
36973,New Jersey,Warren,2018,357,294,62,1,112,60,35,82.352941,17.366947,0.280112

In [31]:
CT_df = aqi_df.loc[aqi_df["State"] == "Connecticut"]

In [32]:
CT_2018_df = CT_df.loc[CT_df["Year"] == 2018]

In [33]:
Connecticut_df = CT_2018_df.drop(['Days CO', 'Days NO2', 'Days Ozone', 'Days SO2', 'Days PM2.5', 'Days PM10'], axis=1)

In [34]:
Connecticut_df["Bad Days"] = Connecticut_df["Unhealthy for Sensitive Groups Days"] + Connecticut_df["Unhealthy Days"] + Connecticut_df["Very Unhealthy Days"] + Connecticut_df["Hazardous Days"]

In [35]:
Connecticut_df["Max_AQI"] = Connecticut_df["Max AQI"]

In [36]:
Connecticut_df["90th_Percentile_AQI"] = Connecticut_df["90th Percentile AQI"]

In [37]:
Connecticut_df["Median_AQI"] = Connecticut_df["Median AQI"]

In [38]:
Conn_2018_df = Connecticut_df.drop(['Unhealthy for Sensitive Groups Days', 'Unhealthy Days', 'Very Unhealthy Days', 'Hazardous Days', 'Max AQI', '90th Percentile AQI', 'Median AQI'], axis=1)

In [39]:
Conn_2018_df["% Good Days"] = Conn_2018_df["Good Days"]/Conn_2018_df["Days with AQI"]*100

In [40]:
Conn_2018_df["% Moderate Days"] = Conn_2018_df["Moderate Days"]/Conn_2018_df["Days with AQI"]*100

In [41]:
Conn_2018_df["% Bad Days"] = Conn_2018_df["Bad Days"]/Conn_2018_df["Days with AQI"]*100

In [42]:
Conn_2018_df

,State,County,Year,Days with AQI,Good Days,Moderate Days,Bad Days,Max_AQI,90th_Percentile_AQI,Median_AQI,% Good Days,% Moderate Days,% Bad Days
36539,Connecticut,Fairfield,2018,365,258,86,21,185,80,41,70.684932,23.561644,5.753425
36540,Connecticut,Hartford,2018,365,293,70,2,143,61,37,80.273973,19.178082,0.547945
36541,Connecticut,Litchfield,2018,363,319,40,4,133,53,36,87.878788,11.019284,1.101928
36542,Connecticut,Middlesex,2018,208,168,32,8,126,67,40,80.769231,15.384615,3.846154
36543,Connecticut,New Haven,2018,365,276,75,14,156,68,40,75.616438,20.547945,3.835616
36544,Connecticut,New London,2018,315,284,25,6,140,50,35,90.158730,7.936508,1.904762
36545,Connecticut,Tolland,2018,213,189,20,4,140,54,38,88.732394,9.389671,1.877934
36546,Connecticut,Windham,2018,358,332,20,6,129,47,34,92.737430,5.586592,1.675978