# Importing Dependancies

In [1]:
%matplotlib notebook 
%matplotlib inline

import os
import csv
import random
import string
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import requests
import zipfile
from scipy.stats import linregress
import glob

# Reading Files & Creating DataFrames

In [2]:
#Air Quality Index DataFrame
aqi_df = pd.read_csv("../Output/aqi_compiled.csv")

# Analysis & Workings

In [3]:
aqi_df

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days SO2,Days PM2.5,Days PM10
0,Alabama,Autauga,1980,179,122,35,18,4,0,0,177,108,40,0,0,122,57,0,0
1,Alabama,Colbert,1980,274,127,45,63,39,0,0,200,165,56,0,0,0,274,0,0
2,Alabama,Jackson,1980,366,85,110,92,79,0,0,200,200,94,0,0,0,366,0,0
3,Alabama,Jefferson,1980,343,171,109,37,19,7,0,221,140,51,207,0,136,0,0,0
4,Alabama,Lauderdale,1980,274,120,58,77,19,0,0,200,139,56,0,0,0,274,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38474,Wyoming,Sublette,2019,210,127,72,8,3,0,0,200,84,49,0,0,208,0,2,0
38475,Wyoming,Sweetwater,2019,273,210,60,3,0,0,0,133,61,43,0,3,165,0,3,102
38476,Wyoming,Teton,2019,244,209,35,0,0,0,0,87,54,44,1,0,240,0,3,0
38477,Wyoming,Uinta,2019,181,146,34,1,0,0,0,101,58,44,0,0,178,0,0,3
38478,Wyoming,Weston,2019,181,161,20,0,0,0,0,71,51,42,0,0,179,2,0,0

In [4]:
NY_df = aqi_df.loc[aqi_df["State"] == "New York"]

In [5]:
NY_df

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days SO2,Days PM2.5,Days PM10
349,New York,Albany,1980,175,47,74,51,3,0,0,178,114,75,0,0,0,175,0,0
350,New York,Bronx,1980,350,176,122,52,0,0,0,137,106,50,5,36,0,309,0,0
351,New York,Broome,1980,365,218,118,22,7,0,0,177,93,44,10,0,147,208,0,0
352,New York,Chautauqua,1980,338,130,101,79,28,0,0,200,144,66,0,0,0,338,0,0
353,New York,Chemung,1980,359,291,53,13,2,0,0,187,71,36,10,0,226,123,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38044,New York,Steuben,2019,274,263,11,0,0,0,0,62,47,37,2,0,232,0,40,0
38045,New York,Suffolk,2019,273,215,49,9,0,0,0,150,71,43,0,0,245,0,28,0
38046,New York,Tompkins,2019,242,236,6,0,0,0,0,61,45,37,0,0,206,36,0,0
38047,New York,Wayne,2019,208,193,15,0,0,0,0,90,49,39,0,0,208,0,0,0
38048,New York,Westchester,2019,273,240,32,1,0,0,0,105,58,38,0,0,241,0,32,0

In [6]:
NY_1980_df = NY_df.loc[NY_df["Year"] == 1980]

In [7]:
NY_1980_df

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days SO2,Days PM2.5,Days PM10
349,New York,Albany,1980,175,47,74,51,3,0,0,178,114,75,0,0,0,175,0,0
350,New York,Bronx,1980,350,176,122,52,0,0,0,137,106,50,5,36,0,309,0,0
351,New York,Broome,1980,365,218,118,22,7,0,0,177,93,44,10,0,147,208,0,0
352,New York,Chautauqua,1980,338,130,101,79,28,0,0,200,144,66,0,0,0,338,0,0
353,New York,Chemung,1980,359,291,53,13,2,0,0,187,71,36,10,0,226,123,0,0
354,New York,Dutchess,1980,361,244,80,34,2,1,0,201,101,33,46,0,105,210,0,0
355,New York,Erie,1980,365,15,97,204,49,0,0,200,157,114,0,5,10,350,0,0
356,New York,Essex,1980,332,227,57,31,16,1,0,203,122,40,0,0,332,0,0,0
357,New York,Kings,1980,358,86,172,70,16,14,0,232,136,76,0,42,72,244,0,0
358,New York,Monroe,1980,365,35,119,168,41,2,0,207,154,106,6,0,28,331,0,0
359,New York,Nassau,1980,366,140,158,37,17,14,0,266,133,56,15,114,79,158,0,0
360,New York,New York,1980,361,10,163,152,30,6,0,215,150,102,172,10,25,154,0,0
361,New York,Niagara,1980,365,59,138,154,12,2,0,206,130,93,2,0,60,303,0,0
362,New York,Oneida,1980,365,280,54,21,8,2,0,204,84,37,5,0,267,93,0,0
363,New York,Onondaga,1980,365,136,148,75,5,1,0,201,122,61,5,63,84,213,0,0
364,New York,Queens,1980,360,138,148,45,16,13,0,278,129,59,5,72,82,201,0,0
365,New York,Rensselaer,1980,359,186,122,39,12,0,0,200,111,49,5,0,146,208,0,0
366,New York,Richmond,1980,355,132,155,40,22,6,0,225,126,58,0,56,108,191,0,0
367,New York,Schenectady,1980,363,242,116,5,0,0,0,115,75,41,16,0,91,256,0,0
368,New York,St. Lawrence,1980,42,39,3,0,0,0,0,75,43,17,0,0,0,42,0,0
369,New York,Suffolk,1980,366,86,139,110,19,12,0,258,147,84,0,0,106,260,0,0
370,New York,Warren,1980,363,235,90,33,5,0,0,200,102,41,0,0,170,193,0,0
371,New York,Wayne,1980,316,287,21,5,3,0,0,197,50,22,0,0,316,0,0,0
372,New York,Westchester,1980,365,197,96,42,16,14,0,235,143,49,18,12,174,161,0,0

In [8]:
NewYork_df = NY_1980_df.drop(['Days CO', 'Days NO2', 'Days Ozone', 'Days SO2', 'Days PM2.5', 'Days PM10'], axis=1)

In [9]:
NewYork_df["Bad Days"] = NewYork_df["Unhealthy for Sensitive Groups Days"] + NewYork_df["Unhealthy Days"] + NewYork_df["Very Unhealthy Days"] + NewYork_df["Hazardous Days"]

In [10]:
NewYork_df["Max_AQI"] = NewYork_df["Max AQI"]

In [11]:
NewYork_df["90th_Percentile_AQI"] = NewYork_df["90th Percentile AQI"]

In [12]:
NewYork_df["Median_AQI"] = NewYork_df["Median AQI"]

In [13]:
NewYork_df

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Bad Days,Max_AQI,90th_Percentile_AQI,Median_AQI
349,New York,Albany,1980,175,47,74,51,3,0,0,178,114,75,54,178,114,75
350,New York,Bronx,1980,350,176,122,52,0,0,0,137,106,50,52,137,106,50
351,New York,Broome,1980,365,218,118,22,7,0,0,177,93,44,29,177,93,44
352,New York,Chautauqua,1980,338,130,101,79,28,0,0,200,144,66,107,200,144,66
353,New York,Chemung,1980,359,291,53,13,2,0,0,187,71,36,15,187,71,36
354,New York,Dutchess,1980,361,244,80,34,2,1,0,201,101,33,37,201,101,33
355,New York,Erie,1980,365,15,97,204,49,0,0,200,157,114,253,200,157,114
356,New York,Essex,1980,332,227,57,31,16,1,0,203,122,40,48,203,122,40
357,New York,Kings,1980,358,86,172,70,16,14,0,232,136,76,100,232,136,76
358,New York,Monroe,1980,365,35,119,168,41,2,0,207,154,106,211,207,154,106
359,New York,Nassau,1980,366,140,158,37,17,14,0,266,133,56,68,266,133,56
360,New York,New York,1980,361,10,163,152,30,6,0,215,150,102,188,215,150,102
361,New York,Niagara,1980,365,59,138,154,12,2,0,206,130,93,168,206,130,93
362,New York,Oneida,1980,365,280,54,21,8,2,0,204,84,37,31,204,84,37
363,New York,Onondaga,1980,365,136,148,75,5,1,0,201,122,61,81,201,122,61
364,New York,Queens,1980,360,138,148,45,16,13,0,278,129,59,74,278,129,59
365,New York,Rensselaer,1980,359,186,122,39,12,0,0,200,111,49,51,200,111,49
366,New York,Richmond,1980,355,132,155,40,22,6,0,225,126,58,68,225,126,58
367,New York,Schenectady,1980,363,242,116,5,0,0,0,115,75,41,5,115,75,41
368,New York,St. Lawrence,1980,42,39,3,0,0,0,0,75,43,17,0,75,43,17
369,New York,Suffolk,1980,366,86,139,110,19,12,0,258,147,84,141,258,147,84
370,New York,Warren,1980,363,235,90,33,5,0,0,200,102,41,38,200,102,41
371,New York,Wayne,1980,316,287,21,5,3,0,0,197,50,22,8,197,50,22
372,New York,Westchester,1980,365,197,96,42,16,14,0,235,143,49,72,235,143,49

In [14]:
NewYork_1980_df = NewYork_df.drop(['Unhealthy for Sensitive Groups Days', 'Unhealthy Days', 'Very Unhealthy Days', 'Hazardous Days', 'Max AQI', '90th Percentile AQI', 'Median AQI'], axis=1)

In [15]:
NewYork_1980_df["% Good Days"]=NewYork_1980_df["Good Days"]/NewYork_1980_df["Days with AQI"]*100

In [16]:
NewYork_1980_df["% Moderate Days"]=NewYork_1980_df["Moderate Days"]/NewYork_1980_df["Days with AQI"]*100

In [17]:
NewYork_1980_df["% Bad Days"]=NewYork_1980_df["Bad Days"]/NewYork_1980_df["Days with AQI"]*100

In [18]:
NewYork_1980_df

,State,County,Year,Days with AQI,Good Days,Moderate Days,Bad Days,Max_AQI,90th_Percentile_AQI,Median_AQI,% Good Days,% Moderate Days,% Bad Days
349,New York,Albany,1980,175,47,74,54,178,114,75,26.857143,42.285714,30.857143
350,New York,Bronx,1980,350,176,122,52,137,106,50,50.285714,34.857143,14.857143
351,New York,Broome,1980,365,218,118,29,177,93,44,59.726027,32.328767,7.945205
352,New York,Chautauqua,1980,338,130,101,107,200,144,66,38.461538,29.881657,31.656805
353,New York,Chemung,1980,359,291,53,15,187,71,36,81.058496,14.763231,4.178273
354,New York,Dutchess,1980,361,244,80,37,201,101,33,67.590028,22.160665,10.249307
355,New York,Erie,1980,365,15,97,253,200,157,114,4.109589,26.575342,69.315068
356,New York,Essex,1980,332,227,57,48,203,122,40,68.373494,17.168675,14.457831
357,New York,Kings,1980,358,86,172,100,232,136,76,24.022346,48.044693,27.932961
358,New York,Monroe,1980,365,35,119,211,207,154,106,9.589041,32.602740,57.808219
359,New York,Nassau,1980,366,140,158,68,266,133,56,38.251366,43.169399,18.579235
360,New York,New York,1980,361,10,163,188,215,150,102,2.770083,45.152355,52.077562
361,New York,Niagara,1980,365,59,138,168,206,130,93,16.164384,37.808219,46.027397
362,New York,Oneida,1980,365,280,54,31,204,84,37,76.712329,14.794521,8.493151
363,New York,Onondaga,1980,365,136,148,81,201,122,61,37.260274,40.547945,22.191781
364,New York,Queens,1980,360,138,148,74,278,129,59,38.333333,41.111111,20.555556
365,New York,Rensselaer,1980,359,186,122,51,200,111,49,51.810585,33.983287,14.206128
366,New York,Richmond,1980,355,132,155,68,225,126,58,37.183099,43.661972,19.154930
367,New York,Schenectady,1980,363,242,116,5,115,75,41,66.666667,31.955923,1.377410
368,New York,St. Lawrence,1980,42,39,3,0,75,43,17,92.857143,7.142857,0.000000
369,New York,Suffolk,1980,366,86,139,141,258,147,84,23.497268,37.978142,38.524590
370,New York,Warren,1980,363,235,90,38,200,102,41,64.738292,24.793388,10.468320
371,New York,Wayne,1980,316,287,21,8,197,50,22,90.822785,6.645570,2.531646
372,New York,Westchester,1980,365,197,96,72,235,143,49,53.972603,26.301370,19.726027

In [19]:
NJ_df = aqi_df.loc[aqi_df["State"] == "New Jersey"]

In [20]:
NJ_1980_df = NJ_df.loc[NJ_df["Year"] == 1980]

In [21]:
NewJersey_df = NJ_1980_df.drop(['Days CO', 'Days NO2', 'Days Ozone', 'Days SO2', 'Days PM2.5', 'Days PM10'], axis=1)

In [22]:
NewJersey_df["Bad Days"] = NewJersey_df["Unhealthy for Sensitive Groups Days"] + NewJersey_df["Unhealthy Days"] + NewJersey_df["Very Unhealthy Days"] + NewJersey_df["Hazardous Days"]

In [23]:
NewJersey_df["Max_AQI"] = NewJersey_df["Max AQI"]

In [24]:
NewJersey_df["90th_Percentile_AQI"] = NewJersey_df["90th Percentile AQI"]

In [25]:
NewJersey_df["Median_AQI"] = NewJersey_df["Median AQI"]

In [26]:
NewJersey_1980_df = NewJersey_df.drop(['Unhealthy for Sensitive Groups Days', 'Unhealthy Days', 'Very Unhealthy Days', 'Hazardous Days', 'Max AQI', '90th Percentile AQI', 'Median AQI'], axis=1)

In [27]:
NewJersey_1980_df["% Good Days"]=NewJersey_1980_df["Good Days"]/NewJersey_1980_df["Days with AQI"]*100

In [28]:
NewJersey_1980_df["% Moderate Days"]=NewJersey_1980_df["Moderate Days"]/NewJersey_1980_df["Days with AQI"]*100

In [29]:
NewJersey_1980_df["% Bad Days"]=NewJersey_1980_df["Bad Days"]/NewJersey_1980_df["Days with AQI"]*100

In [30]:
NewJersey_1980_df

,State,County,Year,Days with AQI,Good Days,Moderate Days,Bad Days,Max_AQI,90th_Percentile_AQI,Median_AQI,% Good Days,% Moderate Days,% Bad Days
323,New Jersey,Atlantic,1980,328,115,139,74,238,154,63,35.060976,42.378049,22.560976
324,New Jersey,Bergen,1980,323,145,123,55,218,129,57,44.891641,38.080495,17.027864
325,New Jersey,Burlington,1980,325,110,113,102,286,182,64,33.846154,34.769231,31.384615
326,New Jersey,Camden,1980,341,125,113,103,239,159,70,36.656891,33.137830,30.205279
327,New Jersey,Cape May,1980,233,142,39,52,219,143,43,60.944206,16.738197,22.317597
328,New Jersey,Cumberland,1980,287,148,91,48,209,115,50,51.567944,31.707317,16.724739
329,New Jersey,Essex,1980,351,123,160,68,215,115,62,35.042735,45.584046,19.373219
330,New Jersey,Gloucester,1980,49,12,23,14,119,114,82,24.489796,46.938776,28.571429
331,New Jersey,Hudson,1980,317,104,153,60,222,126,64,32.807571,48.264984,18.927445
332,New Jersey,Hunterdon,1980,215,109,35,71,217,187,50,50.697674,16.279070,33.023256
333,New Jersey,Mercer,1980,308,175,57,76,230,169,46,56.818182,18.506494,24.675325
334,New Jersey,Middlesex,1980,328,123,119,86,260,143,61,37.500000,36.280488,26.219512
335,New Jersey,Monmouth,1980,316,132,137,47,246,147,55,41.772152,43.354430,14.873418
336,New Jersey,Morris,1980,315,75,171,69,227,166,71,23.809524,54.285714,21.904762
337,New Jersey,Ocean,1980,294,210,84,0,88,61,41,71.428571,28.571429,0.000000
338,New Jersey,Passaic,1980,277,210,64,3,108,64,39,75.812274,23.104693,1.083032
339,New Jersey,Salem,1980,298,235,50,13,164,75,28,78.859060,16.778523,4.362416
340,New Jersey,Somerset,1980,321,200,93,28,209,97,44,62.305296,28.971963,8.722741
341,New Jersey,Union,1980,344,119,140,85,233,161,64,34.593023,40.697674,24.709302
342,New Jersey,Warren,1980,299,194,101,4,106,78,41,64.882943,33.779264,1.337793

In [31]:
CT_df = aqi_df.loc[aqi_df["State"] == "Connecticut"]

In [32]:
CT_1980_df = CT_df.loc[CT_df["Year"] == 1980]

In [33]:
Connecticut_df = CT_1980_df.drop(['Days CO', 'Days NO2', 'Days Ozone', 'Days SO2', 'Days PM2.5', 'Days PM10'], axis=1)

In [34]:
Connecticut_df["Bad Days"] = Connecticut_df["Unhealthy for Sensitive Groups Days"] + Connecticut_df["Unhealthy Days"] + Connecticut_df["Very Unhealthy Days"] + Connecticut_df["Hazardous Days"]

In [35]:
Connecticut_df["Max_AQI"] = Connecticut_df["Max AQI"]

In [36]:
Connecticut_df["90th_Percentile_AQI"] = Connecticut_df["90th Percentile AQI"]

In [37]:
Connecticut_df["Median_AQI"] = Connecticut_df["Median AQI"]

In [38]:
Conn_1980_df = Connecticut_df.drop(['Unhealthy for Sensitive Groups Days', 'Unhealthy Days', 'Very Unhealthy Days', 'Hazardous Days', 'Max AQI', '90th Percentile AQI', 'Median AQI'], axis=1)

In [39]:
Conn_1980_df["% Good Days"] = Conn_1980_df["Good Days"]/Conn_1980_df["Days with AQI"]*100

In [40]:
Conn_1980_df["% Moderate Days"] = Conn_1980_df["Moderate Days"]/Conn_1980_df["Days with AQI"]*100

In [41]:
Conn_1980_df["% Bad Days"] = Conn_1980_df["Bad Days"]/Conn_1980_df["Days with AQI"]*100

In [42]:
Conn_1980_df

,State,County,Year,Days with AQI,Good Days,Moderate Days,Bad Days,Max_AQI,90th_Percentile_AQI,Median_AQI,% Good Days,% Moderate Days,% Bad Days
76,Connecticut,Fairfield,1980,366,35,104,227,289,219,120,9.562842,28.415301,62.021858
77,Connecticut,Hartford,1980,366,115,193,58,260,126,60,31.420765,52.732240,15.846995
78,Connecticut,Litchfield,1980,164,95,26,43,269,182,44,57.926829,15.853659,26.219512
79,Connecticut,Middlesex,1980,164,69,38,57,267,218,67,42.073171,23.170732,34.756098
80,Connecticut,New Haven,1980,366,157,134,75,295,150,59,42.896175,36.612022,20.491803
81,Connecticut,Tolland,1980,148,72,27,49,223,182,54,48.648649,18.243243,33.108108